
{'date': 'Wed Dec 16 2020 18:05:04.352 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  botao_caixa = Elemento(botao_seta, tit="CLIQUE",
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Dec 16 2020 18:06:15.976 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 41
  botao_caixa = Elemento(Imagem_Biblioteca_caixa, tit="CLIQUE",
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Dec 16 2020 18:07:16.693 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 46
  def clique_caixa (event = None):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Dec 16 2020 18:08:25.275 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 41
    botao_caixa = Elemento(Imagem_Biblioteca_caixa, tit="CLIQUE",
NameError: name 'clique_caixa' is not defined
'''},
{'date': 'Wed Dec 16 2020 18:08:44.534 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 41
    botao_caixa = Elemento(Imagem_Biblioteca_caixa, tit="CLIQUE",
NameError: name 'clique_caixa' is not defined
'''},
{'date': 'Wed Dec 16 2020 18:09:58.332 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 41
    botao_caixa = Elemento(Imagem_Biblioteca_caixa, tit="CLIQUE",
NameError: name 'clique_caixa' is not defined
'''},
{'date': 'Wed Dec 16 2020 18:10:10.436 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 41
    botao_caixa = Elemento(Imagem_Biblioteca_caixa, tit="CLIQUE",
NameError: name 'clique_caixa' is not defined
'''},
{'date': 'Tue Jan 26 2021 15:22:39.486 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 46
  cena = self.Biblioteca_dentro,
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Jan 26 2021 15:35:52.218 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 96
    desafio_2().inicia()
  module <module> line 59
    self.BONECA3= Elemento(imagem_boneca2, tit="Hipátia",
AttributeError: 'desafio_2' object has no attribute 'Biblioteca_dentro'
'''},
{'date': 'Tue Jan 26 2021 17:12:26.653 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 110
    desafio_2().inicia()
  module <module> line 80
    self.CAIXA_ABERTA("click", self.CAIXA_ABRE)
TypeError: 'Elemento' object is not callable
'''},