
{'date': 'Tue Jan 26 2021 14:28:47.774 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 20
  def resgata(self,x,y,w,h):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Jan 26 2021 14:30:05.720 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 14
  """Aciona estado de inv.bota = True para que eventual clique devolva o Elemento para a cena"""
  ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Jan 26 2021 14:30:17.277 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 17
  """Método vai do Elemento atrelado ao evento de reposicionamento, onde o memento especifica os argumentos pedidos pelo método resgata."""
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Jan 26 2021 14:30:49.681 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 32
  self.memento=memento
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Jan 26 2021 14:31:11.747 GMt-0300 (Hora padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 32
  self.memento=memento
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Feb 08 2021 14:13:03.713 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 38
    Main()
  module <module> line 29
    self.T_AZUL=Item_herdado(triangulo_azul, tit="nome_do_meu_elemento", 
NameError: name 'Item_herdado' is not defined
'''},
{'date': 'Mon Feb 08 2021 16:29:06.193 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 78
    desafio_teorema().inicia()
  module <module> line 71
    self.texto_1= Texto(self.BIBLIOTECA, txt= 'Clique no quadrado vermelho para completar o quebra-cabeça. Escolha a melhor imagem que complete aquela posição.')
NameError: name 'Texto' is not defined
'''},
{'date': 'Mon Feb 08 2021 17:31:17.980 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 300
  def desafio4(self,*_):
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Feb 08 2021 17:31:35.442 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 312
    desafio_teorema().inicia()
  module <module> line 265
    self.T_AMARELO5.elt.bind("click", self.desafio5)
AttributeError: 'desafio_teorema' object has no attribute 'desafio5'
'''},
{'date': 'Mon Feb 08 2021 17:42:52.220 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 383
    desafio_teorema().inicia()
  module <module> line 245
    self.DESAFIO7= Elemento(desafio, tit="Hipátia",
AttributeError: 'desafio_teorema' object has no attribute 'BIBLIOTECA7'
'''},
{'date': 'Wed Feb 24 2021 14:55:06.263 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 385
    desafio_teorema().inicia()
  module <module> line 82
    self.QUADRADO_VERMELHO = Elemento (quadrado_vermelho, tit="nome_do_meu_elemento", 
NameError: name 'quadrado_vermelho' is not defined
'''},
{'date': 'Tue Mar 16 2021 21:09:39.903 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 391
    desafio_teorema().inicia()
  module <module> line 59
    self.BONECA2= Elemento(imagem_boneca2, tit="Hipátia",
NameError: name 'imagem_boneca2' is not defined
'''},
{'date': 'Tue Mar 16 2021 21:24:25.135 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 396
    desafio_teorema().inicia()
  module <module> line 266
    self.texto_2_2=Texto(self.Biblioteca_porta, txt= "A porta esta trancada. Resolva o desafio para abri-la" )
AttributeError: 'desafio_teorema' object has no attribute 'Biblioteca_porta'
'''},
{'date': 'Tue Mar 16 2021 21:24:49.67 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 396
    desafio_teorema().inicia()
  module <module> line 333
    self.BOTAO.elt.bind("click", self.abre_porta)
AttributeError: 'desafio_teorema' object has no attribute 'BOTAO'
'''},
{'date': 'Tue Mar 16 2021 21:25:13.586 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 396
    desafio_teorema().inicia()
  module <module> line 333
    self.PORTA.elt.bind("click", self.abre_porta)
AttributeError: 'desafio_teorema' object has no attribute 'PORTA'
'''},