
{'date': 'Wed Mar 24 2021 20:34:50.593 GMt-0300 (GMT-03:00) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 40
    ATO4().inicia()                    
  module <module> line 32
    self.HIPATIA_COSTAS = Elemento(imagem_hipatiacostas, tit="CLIQUE",
AttributeError: 'ATO4' object has no attribute 'CABANAFORA'
'''},
{'date': 'Wed Mar 24 2021 20:35:04.707 GMt-0300 (GMT-03:00) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 40
    ATO4().inicia()                    
AttributeError: 'ATO4' object has no attribute 'inicia'
'''},
{'date': 'Wed Mar 24 2021 20:35:29.439 GMt-0300 (GMT-03:00) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 40
    ATO4().vai()                    
AttributeError: 'ATO4' object has no attribute 'vai'
'''},
{'date': 'Wed Mar 24 2021 20:36:04.651 GMt-0300 (GMT-03:00) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 40
    ATO4().inicia()                    
AttributeError: 'ATO4' object has no attribute 'inicia'
'''},
{'date': 'Wed Mar 24 2021 20:42:23.168 GMt-0300 (GMT-03:00) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 50
    ATO4().inicia()                    
  module <module> line 42
    self.HIPATIA_COSTAS.elt.bind("click", self.ENTROU)
AttributeError: 'ATO4' object has no attribute 'ENTROU'
'''},
{'date': 'Thu Mar 25 2021 16:20:47.418 GMt-0300 (GMT-03:00) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 73
    ATO4().inicia()                    
  module <module> line 48
    self.texto_2 = Texto(self.CABANA_DENTRO, txt= "Ao entrar, Hipátia se deparou com alguém e se espantou. Era sua mãe. Clique na mãe da Hipátia para saber o que ela tem a dizer.")
AttributeError: 'ATO4' object has no attribute 'CABANA_DENTRO'
'''},
{'date': 'Thu Mar 25 2021 16:27:56.372 GMt-0300 (GMT-03:00) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 45
    ATO4().inicia()                    
  module <module> line 32
    self.ABRE_PORTA.elt.bind("click", self.PORTA_ABRE)
AttributeError: 'ATO4' object has no attribute 'ABRE_PORTA'
'''},
{'date': 'Thu Mar 25 2021 16:31:22.59 GMt-0300 (GMT-03:00) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 50
    ATO4().inicia()                    
  module <module> line 28
    self.SETA_1 = Elemento(imagem_seta1, tit="CLIQUE",
AttributeError: 'ATO4' object has no attribute 'CABANA_DENTRO'
'''},
{'date': 'Thu Mar 25 2021 16:38:12.726 GMt-0300 (GMT-03:00) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 69
    ATO4().inicia()                    
  module <module> line 51
    self.SETA_1.elt.bind("click", self.DIALOGO2)
AttributeError: 'ATO4' object has no attribute 'DIALOGO2'
'''},